version: 1.1.0.{build}

environment:
  packageVersion: 1.1.0

image: Visual Studio 2022

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion"
- ps: Update-AppveyorBuild -Version $env:buildVersion

configuration: Release

before_build:
- nuget restore
- cmd: dotnet restore

build:
  verbosity: minimal

after_build:
- ps: nuget pack Fluent-Regex.nuspec -version "$env:nugetVersion"

artifacts:
- path: 'Fluent-Regex*.nupkg'
  name: nuget-package

deploy:
- provider: NuGet
  api_key:
    secure: l/JE/7yoZOCqSTvqE99Q/0XT1nFsiU3I+yT6o+WshW030w5/mu0pbOrQL3ko86sT
  artifact: nuget-package
  on:
    branch: master
