version: 1.0.1.{build}

environment:
  packageVersion: 1.0.1

image: Visual Studio 2022

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion"
- ps: Update-AppveyorBuild -Version $env:buildVersion

configuration: Release

before_build:
- nuget restore
- cmd: dotnet restore

build:
  verbosity: minimal

after_build:
- ps: nuget pack Fluent-Regex.nuspec -version "$env:nugetVersion"

artifacts:
- path: 'Fluent-Regex*.nupkg'
  name: nuget-package

deploy:
- provider: NuGet
  api_key:
    secure: UE1U6fltlFxt5ltmmkQ2xLbb3sAc5QNdt6SwJ1Z0wcgqoOsmbytwjpyKHu7j0ySQ
  artifact: nuget-package
  on:
    branch: master
